### PR TITLE
Allowing override methods in connection definition, resolves #58

### LINKED ISSUE #58: Changing REST method on 0.1.0
On 0.0.4 the configuration contained the method to use for the appropriate action. In there an equivalent for 0.1.0? I have an endpoint that uses PATCH instead of POST for updates.

### PR DESCRIPTION
**Pull request by wwhurley**
Added configuration methods copied from 0.0.4 in the connection definition.

### CODE REVIEW

**Comment by wwhurley** [comment]
I don't know Superagent very well, would it be possible to create the request prior to having the endpoint defined and then set it after all of the hooks run?

**Comment by zohararad** [comment]
@wwhurley I think it's possible to define the request and then assign the end-point later on. However, I did want this to run as soon as possible, to allow hooks to modify both. Why can't this be done first?

**Comment by wwhurley** [comment]
So our flow should be:
# Create request with the HTTP method from the connection configuration
# Call hooks, passing the request object and HTTP method
# Update the request with the endpoint as returned from hooks

**Comment by zohararad** [comment]
Ok - it was actually easier to pull your code and refactor.

Superagent is a bit annoying in the sense that you have to call the HTTP method with an endpoint on the request object to get a valid request instance. I ended up leaving that bit inside the hooks forEach loop but added another condition to ensure that the request object is created only once, if it's undefined.

So the flow is:

1. Run hooks
2. Create request object from HTTP method and endpoint as soon as both are available
3. Run additional hooks
4. Return request instance

**Pull request merged**
