### PR TITLE
refactors hooks to be async

### PR DESCRIPTION
**Pull request by jakutis**
This enables calling async functions inside the hooks, before returning
the request/response.

### CODE REVIEW

**Comment by jakutis** [comment]
Hey, an example would be using Contents section of GitHub API.
The exact reason is this: one must first acquire `sha` (see [sha parameter being required](https://developer.github.com/v3/repos/contents/#update-a-file) of current file so that one could update the file with new contents.

So an example (may not work, just for illustration purposes) for sails-rest would be:

```javascript
var got = require('got');
var headers = {
  'X-GitHub-Media-Type': 'github.v3',
  'Authorization': 'token ' + GitHubCredentials.token
};
var connection = {
      adapter: 'sails-rest',
      host: 'api.github.com',
      protocol: 'https',
      pathname: '',
      headers: headers,
      methods: {
        create: 'put'
      },
      hooks: {
        merge:    false,
        before:   [
          function (req, method, config, conn, cb) {
            config.endpoint = 'https://api.github.com/repos/john/random-app/contents' + conn.values.path;
            cb();
          },
          function (req, method, config, conn, cb) {
            if (method === 'put') {
              got(config.endpoint, {
                headers: headers
              }, function (err, data) {
                var sha;
                if (!err) {
                  sha = JSON.parse(data).sha;
                }
                conn.values = {
                  message: 'a random float',
                  committer: {
                    name: GitHubCredentials.username,
                    email: GitHubCredentials.email
                  },
                  content: new Buffer(conn.values.text).toString('base64'),
                  branch: 'master',
                  sha: sha
                });
                conn.options = {};
                cb();
              });
            } else if (method === 'get') {
              conn.options = {};
              cb();
            }
          }
        ]
      }
    };
```

**Comment by zohararad** [comment]
So, my question is, why do you have to move this logic into the library. Why not simply implement your own async logic inside the before hooks?

On the previous versions of the library, there was too much logic added by other contributors that ended up bloating and complicating the code. The purpose of the before hooks is to allow users to implement their own logic without adding it to the core library.

I'm not 100% convinced this is something that must be part of the core code, since it can probably be implemented separately as mentioned above. Do you agree? Or am I missing something here?

**Comment by jakutis** [comment]
@zohararad I do not agree, you are missing the thing that I must do some async logic (i.e. an HTTP request) in inside my before hook. Only after it finishes, I can let sails-rest proceed with making its HTTP request. That is because I must use results of my async logic to modify the sails-rest HTTP request headers or body.

I fully agree with you that sails-rest should have no logic and require the logic to be executed in hooks. But, it is a good chance that at least some of my logic in hooks is async. Since sails-rest `v0.1.0-waterline-v0.10` branch supported only sync hook logic, I ask you to consider this pull request to be not a feature addition, but a bug fix.

**Comment by zohararad** [comment]
@jakutis I'm not ignoring that, I'm only asking why can't this async logic be part of your own hooks?

Why can't you implement something like this (apologies for imprecise async implementation):

```
function myBeforeHook(req, method, config, conn, cb){
  var firstInternalAsync = function(){
    // run something
  }
  var secondInternalAsync = function(){
    // run something
  }
  async.eachSeries([firstInternalAsync, secondInternalAsync, cb])....
}
```

**Comment by jakutis** [comment]
@zohararad because there is no cb argument passed for hooks with your current implementation

**Comment by zohararad** [comment]
Ok - I get it now (sorry for being a bit stubborn, old habits I guess. I want to try and keep sails-rest as clean as possible).

Could I please ask you for a couple of small changes though:

1. Please change async `cb` arg name to `nextHook` or something similar? I want to make a clear distinction between the callback passed to the connection and internal `async` callbacks (see lines 30 and 57 for example)
2. L87 `err2` should also be named into something a bit more meaningful

I'll pull and review the code once more after that and merge if all is good :)

**Comment by jakutis** [comment]
@zohararad sure, you can review now.

**Comment by zohararad** [comment]
Done. Sorry for the delay and thanks for the PR and for your patience in the discussion above.

**Comment by jakutis** [comment]
Thank you! No problem for delay and actually I am sorry, because the changes that I did in README were not so good, so I needed to create another pull request: #68

**Pull request merged**
